name: Pet App GitHub Pipeline

on:
  push:
    branches: ["suhana-backup"]
  pull_request:
    branches: ["suhana-backup"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend build
        working-directory: frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/suhana-backup'

    steps:
      - name: Deploy to VM using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/Pet-Controller/pet-app-cicd
            git pull origin suhana-backup
            sudo docker compose down
            sudo docker compose up -d --build
